<script lang="ts">
 import {onMount} from 'svelte';import {Api} from '$lib/api';
 let cases=$state<any[]>([]), recordings=$state<any[]>([]), selected=$state<any>(null),name=$state(''),description=$state(''),attachment=$state(''),note=$state(''),error=$state('');
 async function load(){try{cases=await Api.cases();recordings=(await Api.recordings()).items||[];if(selected)selected=await Api.case(selected.id);error=''}catch(e){error=String(e)}}
 async function create(){if(!name.trim())return;await Api.createCase({name:name.trim(),description,status:'open',tags:''});name='';description='';await load()}
 async function open(c:any){selected=await Api.case(c.id)}
 async function attach(){if(!selected||!attachment)return;await Api.attachCase(selected.id,{kind:'recording',ref:attachment,note});attachment='';note='';selected=await Api.case(selected.id)}
 onMount(load);
</script>
<div class="page"><h1>Cases</h1><p class="muted">Attach validated recordings and evidence notes to investigation cases.</p>{#if error}<p class="error">{error}</p>{/if}<section class="card form"><input bind:value={name} placeholder="Case name"><input bind:value={description} placeholder="Description"><button onclick={create}>Create</button></section><div class="grid"><section class="card">{#each cases as c}<div class="row"><button onclick={()=>open(c)}><b>{c.name}</b> · {c.status}</button><button class="danger" onclick={()=>Api.deleteCase(c.id).then(load)}>Delete</button></div>{:else}<p class="muted">No cases.</p>{/each}</section>{#if selected}<section class="card"><h2>{selected.name}</h2><p>{selected.description}</p><div class="form"><select bind:value={attachment}><option value="">Choose recording</option>{#each recordings as r}<option value={r.name}>{r.name}</option>{/each}</select><input bind:value={note} placeholder="Attachment note"><button onclick={attach}>Attach</button></div>{#each selected.attachments||[] as a}<div class="row"><span><b>{a.kind}</b>: {a.ref}<br><span class="muted">{a.note}</span></span><button onclick={()=>Api.deleteCaseAttachment(a.id).then(()=>open(selected))}>Remove</button></div>{:else}<p class="muted">No attachments.</p>{/each}</section>{/if}</div></div>
<style>.page{padding:16px;overflow:auto;height:100%}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px}.card{padding:14px;background:var(--bg-elev);border:1px solid var(--line);border-radius:8px;margin:12px 0}.form,.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.row{justify-content:space-between;padding:9px 0;border-bottom:1px solid var(--line)}input,select,button{background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:7px;border-radius:4px}.muted{color:var(--fg-dim)}.error,.danger{color:var(--danger)}</style>
