<script lang="ts">
  import { onMount } from 'svelte';
  import { Api } from '$lib/api';
  let packs = $state<any[]>([]); let slices = $state<any[]>([]); let error = $state(''); let busy = $state<string | null>(null);
  async function load() { try { const [data, plans]:any = await Promise.all([Api.featurePacks(), Api.protocolSlices()]); packs = data.groups ?? data.packs ?? data ?? []; slices = plans; error = ''; } catch (e) { error = String(e); } }
  onMount(load);
  async function toggle(pack:any) { busy = pack.id; try { await Api.featurePackEnable(pack.id, !pack.enabled); await load(); } catch (e) { error = String(e); } finally { busy = null; } }
</script>
<div class="page"><div class="heading"><div><h1>Feature Packs</h1><p class="muted">Configuration is not decoder availability. Protocols remain unavailable until recorded IQ passes end to end.</p></div><button onclick={load}>Refresh</button></div>{#if error}<p class="error">{error}</p>{/if}<h2>Decoder dependencies</h2><div class="grid">{#each packs as pack}<section class="card"><div class="title"><h2>{pack.name ?? pack.id}</h2><button disabled={busy===pack.id} class:enabled={pack.enabled} onclick={() => toggle(pack)}>{pack.enabled ? 'Enabled' : 'Disabled'}</button></div><p class="muted">{pack.path || 'No executable configured'}</p><p>Protocols: {(pack.protocols ?? []).join(', ')}</p><small class:ok={pack.enabled}>{pack.enabled ? 'Configured enabled' : 'Configured disabled'}</small></section>{:else}<section class="card empty">No feature packs reported</section>{/each}</div><h2>Tracked protocol slices</h2><div class="grid">{#each slices as row}<section class="card"><div class="title"><h2>{row.slice.name}</h2><small class="unavailable">UNAVAILABLE</small></div><p>{row.slice.frequency_plan}</p><p class="muted">RF {row.slice.rf_bandwidth_hz.toLocaleString()} Hz · IQ ≥ {row.slice.required_sample_rate_hz.toLocaleString()} sample/s</p><p>{row.slice.ui_outcome}</p><small class:ok={row.hardware.supported}>{row.hardware.supported ? 'Hardware suitable; decoder incomplete' : (row.hardware.reasons ?? []).join('; ')}</small>{#if row.hardware.guidance?.length}<p class="muted">{row.hardware.guidance.join(' ')}</p>{/if}</section>{/each}</div></div>
<style>.page{padding:16px;overflow-y:auto;height:100%}.heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.muted,.empty{color:var(--fg-dim)}.error,.unavailable{color:var(--danger)}button{background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:7px 11px;border-radius:5px;cursor:pointer}.title{display:flex;justify-content:space-between;align-items:center;gap:8px}.title button.enabled{color:var(--ok);border-color:var(--ok)}button:disabled{opacity:.5}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px;margin:10px 0 22px}.card{padding:14px;background:var(--bg-elev);border:1px solid var(--line);border-radius:8px}h2{font-size:15px;margin:12px 0 0}.title h2{margin:0}.ok{color:var(--ok)}small{font:11px var(--mono)}p{font-size:12px}</style>
