<script lang="ts">
  import { onMount } from 'svelte';
  import { Api } from '$lib/api';
  let packs = $state<any[]>([]); let dependencies = $state<any[]>([]); let error = $state(''); let busy = $state<string | null>(null);
  async function load() { try { const [data, deps]:any[] = await Promise.all([Api.featurePacks(), fetch('http://127.0.0.1:8765/sidecars/status').then(r=>r.json())]); packs = data.groups ?? data.packs ?? data ?? []; dependencies = deps.discovered ?? []; error = ''; } catch (e) { error = String(e); } }
  function packDeps(pack:any) { return dependencies.filter(d => (pack.protocols ?? []).includes(d.protocol)); }
  onMount(load);
  async function toggle(pack:any) { busy = pack.id; try { await Api.featurePackEnable(pack.id, !pack.enabled); await load(); } catch (e) { error = String(e); } finally { busy = null; } }
</script>
<div class="page"><div class="heading"><div><h1>Feature Packs</h1><p class="muted">A pack is usable only after its decoder passes a transport health check.</p></div><button onclick={load}>Refresh</button></div>{#if error}<p class="error">{error}</p>{/if}<div class="grid">{#each packs as pack}<section class="card"><div class="title"><h2>{pack.name ?? pack.id}</h2><button disabled={busy===pack.id} class:enabled={pack.enabled} onclick={() => toggle(pack)}>{pack.enabled ? 'Enabled' : 'Disabled'}</button></div><p>Protocols: {(pack.protocols ?? []).join(', ')}</p>{#each packDeps(pack) as d}<p><b>{d.name}</b> {d.healthy ? 'Healthy' : `Unavailable: ${d.health}`}<br/><small>{d.installed_version ?? 'not installed'} · {d.license} ({d.license_accepted ? 'accepted' : 'acceptance required'}) · {d.platform_supported ? 'supported' : 'unsupported platform'}</small></p>{/each}<small class:ok={pack.enabled && packDeps(pack).some(d=>d.healthy)}>{pack.enabled && packDeps(pack).some(d=>d.healthy) ? 'Available' : 'Not available'}</small></section>{:else}<section class="card empty">No feature packs reported</section>{/each}</div></div>
<style>.page{padding:16px;overflow-y:auto;height:100%}.heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.muted,.empty{color:var(--fg-dim)}.error{color:var(--danger)}button{background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:7px 11px;border-radius:5px;cursor:pointer}.title{display:flex;justify-content:space-between;align-items:center;gap:8px}.title button.enabled{color:var(--ok);border-color:var(--ok)}button:disabled{opacity:.5}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}.card{padding:14px;background:var(--bg-elev);border:1px solid var(--line);border-radius:8px}h2{font-size:15px;margin:0}.ok{color:var(--ok)}small{font:11px var(--mono)}p{font-size:12px}</style>
