<script lang="ts">
 import {onMount} from 'svelte'; import OfflineMap from '$lib/OfflineMap.svelte'; import {Api,type PositionEvent} from '$lib/api';
 let kind=$state('');let filter=$state('');let points=$state<PositionEvent[]>([]);let selected=$state<PositionEvent>();let error=$state('');let inspect=$state(false);let trailHours=$state(24);
 async function load(){try{let q=new URLSearchParams();if(kind)q.set('kind',kind);q.set('from_ms',String(Date.now()-trailHours*3600000));q.set('limit','1000');points=(await Api.trackHistory(q.toString())).items;error=''}catch(e){error=String(e)}}
 let visible=$derived(points.filter(p=>!filter||p.entity_id.toLowerCase().includes(filter.toLowerCase())||JSON.stringify(p.metadata).toLowerCase().includes(filter.toLowerCase())));
 async function save(format:string){let q=new URLSearchParams();if(kind)q.set('kind',kind);q.set('limit','1000');let r=await Api.exportTracks(format,q.toString());let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([r.data],{type:r.content_type}));a.download=`tracks.${format}`;a.click();URL.revokeObjectURL(a.href)}
 onMount(()=>{load();let t=setInterval(load,5000);return()=>clearInterval(t)});
</script>
<div class="page"><h1>Live Tracking</h1><p class="muted">Aircraft, vessels, APRS stations, and radiosondes. Map rendering is fully local and works offline.</p>
<div class="tools"><select bind:value={kind} onchange={load}><option value="">All sources</option><option value="aircraft">Aircraft</option><option value="vessel">Vessels</option><option value="aprs">APRS</option><option value="radiosonde">Radiosondes</option></select><input bind:value={filter} placeholder="Filter ID or metadata"><label>Trail <input type="number" min="1" max="168" bind:value={trailHours} onchange={load}> h</label>{#each ['csv','json','geojson','kml'] as f}<button onclick={()=>save(f)}>{f.toUpperCase()}</button>{/each}</div>
{#if error}<p class="error">{error}</p>{/if}<OfflineMap points={visible} onselect={(p)=>selected=p}/>
<div class="split"><div class="table"><table><thead><tr><th>Type / ID</th><th>Position</th><th>Time</th><th>Source / accuracy</th></tr></thead><tbody>{#each visible as p}<tr class:active={selected?.id===p.id} onclick={()=>selected=p}><td>{p.entity_kind}<br><b>{p.entity_id}</b></td><td>{p.latitude.toFixed(5)}, {p.longitude.toFixed(5)}<br>{p.altitude_m??'—'} m</td><td>{new Date(p.timestamp_ms).toLocaleString()}</td><td>{p.source}<br>±{p.accuracy_m??'unknown'} m</td></tr>{/each}</tbody></table></div>
{#if selected}<aside><h3>{selected.entity_id}</h3><button onclick={()=>inspect=!inspect}>{inspect?'Hide':'Inspect'} message</button><dl><dt>Speed</dt><dd>{selected.speed_mps??'—'} m/s</dd><dt>Heading</dt><dd>{selected.heading_deg??'—'}°</dd><dt>Source message</dt><dd>{selected.source_message_id??'—'}</dd></dl>{#if inspect}<pre>{JSON.stringify(selected.metadata,null,2)}</pre>{/if}</aside>{/if}</div></div>
<style>.page{padding:16px;height:100%;overflow:auto}.muted{color:var(--fg-dim)}.tools{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}.tools input[type=number]{width:55px}.split{display:grid;grid-template-columns:1fr minmax(220px,28%);gap:12px;margin-top:12px}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:7px;border-bottom:1px solid var(--line);font-size:12px}tr{cursor:pointer}tr.active{background:#173142}aside{border:1px solid var(--line);padding:12px}dt{color:var(--fg-dim)}dd{margin:0 0 8px}pre{white-space:pre-wrap;overflow:auto}.error{color:#f66}@media(max-width:700px){.split{grid-template-columns:1fr}}</style>
