<script lang="ts">
 import {onMount} from 'svelte';import {Api} from '$lib/api';
 let iq=$state<any>({});let transcription=$state<any>({});let annotations=$state<any[]>([]);let transcripts=$state<any[]>([]);let error=$state('');
 let iqRunning=$derived(Boolean(iq.recording??iq.running??iq.active));let txRunning=$derived(Boolean(transcription.running??transcription.active));
 async function load(){try{[iq,annotations,transcription,transcripts]=await Promise.all([Api.iqRecordingStatus(),Api.recordingAnnotations(),Api.transcriptionStatus(),Api.transcripts()]);error=''}catch(e){error=String(e)}}onMount(load);
 async function iqToggle(){if(iqRunning)await Api.iqRecordingStop();else await Api.iqRecordingStart();await load()}async function txToggle(){if(txRunning)await Api.transcriptionStop();else await Api.transcriptionStart();await load()}
</script>
<div class="page"><h1>Recording</h1><p class="muted">Manage IQ captures, annotations and audio transcription.</p>{#if error}<p class="error">{error}</p>{/if}<div class="grid"><section class="card"><h2>IQ recording</h2><p class:ok={iqRunning}>{iqRunning?'Recording':'Stopped'}</p><button class="primary" onclick={iqToggle}>{iqRunning?'Stop recording':'Start recording'}</button><pre>{JSON.stringify(iq,null,2)}</pre></section><section class="card"><h2>Transcription</h2><p class:ok={txRunning}>{txRunning?'Running':'Stopped'}</p><button class="primary" onclick={txToggle}>{txRunning?'Stop transcription':'Start transcription'}</button><pre>{JSON.stringify(transcription,null,2)}</pre></section></div><button onclick={load}>Refresh</button><section class="card"><h2>Annotations</h2>{#each annotations as item}<div class="row">{JSON.stringify(item)}</div>{:else}<div class="empty">No annotations</div>{/each}</section><section class="card"><h2>Transcripts</h2>{#each transcripts as item}<div class="row">{typeof item==='object'?JSON.stringify(item):item}</div>{:else}<div class="empty">No transcripts</div>{/each}</section></div>
<style>.page{padding:16px;overflow-y:auto;height:100%}.muted,.empty{color:var(--fg-dim)}.error{color:var(--danger)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.card{margin:12px 0;padding:14px;background:var(--bg-elev);border:1px solid var(--line);border-radius:8px}h2{font-size:14px;margin-top:0}.ok{color:var(--ok)}button{background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:7px 11px;border-radius:5px}.primary{color:var(--accent);border-color:var(--accent)}pre,.row{font:12px var(--mono);word-break:break-word}.row{padding:8px 0;border-top:1px solid var(--line)}pre{background:var(--bg);padding:8px;overflow:auto}.empty{text-align:center;padding:16px}</style>
