<script lang="ts">
 import {onMount} from 'svelte'; import {Api,authenticatedMediaUrl} from '$lib/api';
 let iq=$state<any>({}), library=$state<any>({items:[]}), vfos=$state<any[]>([]), active=$state<any[]>([]), annotations=$state<any[]>([]), error=$state('');
 let note=$state(''), selected=$state(''), offset=$state(0), page=$state(1), tick=$state(Date.now());
 let vox=$state({enabled:true,threshold_db:-42,pre_roll_ms:2000,post_roll_ms:1000});
 async function load(){try{[iq,library,vfos,annotations,{active}]=await Promise.all([Api.iqRecordingStatus(),Api.recordings(page),Api.vfoStates(),Api.recordingAnnotations(),Api.audioRecordingStatus()]);error=''}catch(e){error=String(e)}}
 async function toggleIq(){iq.recording?await Api.iqRecordingStop():await Api.iqRecordingStart();await load()}
 async function toggleRecord(v:any){let r=active.find(x=>x.vfo_id===v.id);if(r)await Api.stopAudioRecording(v.id);else await Api.startAudioRecording(v.id,{frequency_hz:v.frequency_hz,mode:v.mode,vox});await load()}
 async function annotate(){if(!selected||!note.trim())return;await Api.addRecordingAnnotation({recording_path:selected,offset_ms:offset,text:note.trim()});note='';await load()}
 async function remove(name:string){if(confirm(`Delete ${name}?`)){await Api.deleteRecording(name);await load()}}
 async function rename(name:string){let next=prompt('New file name',name);if(next&&next!==name){await Api.renameRecording(name,next);await load()}}
 async function setVolume(v:any,e:Event){await Api.vfoVolume(v.id,Number((e.target as HTMLInputElement).value));await load()}
 onMount(()=>{load();let t=setInterval(()=>tick=Date.now(),1000);return()=>clearInterval(t)});
</script>
<div class="page"><h1>Recording library</h1><p class="muted">Per-VFO WAV capture, VOX and evidence annotations.</p>{#if error}<p class="error">{error}</p>{/if}
<section class="card"><h2>Live VFO audio</h2><div class="vox"><label><input type="checkbox" bind:checked={vox.enabled}> VOX/VAD</label><label>Threshold <input type="number" bind:value={vox.threshold_db}> dB</label><label>Pre-roll <input type="number" bind:value={vox.pre_roll_ms}> ms</label><label>Post-roll <input type="number" bind:value={vox.post_roll_ms}> ms</label></div>
{#each vfos as v}<div class="vfo"><b>VFO {v.id}</b><span>{(v.frequency_hz/1e6).toFixed(5)} MHz {v.mode}</span><audio controls src={authenticatedMediaUrl(`/audio/vfo/${v.id}/stream.wav`)}></audio><button onclick={()=>Api.vfoMute(v.id,!v.muted).then(load)}>{v.muted?'Unmute':'Mute'}</button><input aria-label="Volume" type="range" min="0" max="1" step="0.05" value={v.volume} onchange={(e)=>setVolume(v,e)}>{#if active.find(x=>x.vfo_id===v.id)}<span class="rec">● REC {Math.max(0,Math.floor((tick-active.find(x=>x.vfo_id===v.id).started_ms)/1000))}s</span>{/if}<button onclick={()=>toggleRecord(v)}>{active.find(x=>x.vfo_id===v.id)?'Stop':'Record WAV'}</button></div>{:else}<p class="muted">Start a scanner to expose VFO audio.</p>{/each}</section>
<section class="card"><h2>IQ capture</h2><button onclick={toggleIq}>{iq.recording?'Stop CF32':'Record CF32'}</button> <span>{iq.bytes_written||0} bytes</span></section>
{#if library.disk_warning}<p class="warning">Low disk space: {Math.round((library.disk_free_bytes||0)/1048576)} MiB free. Recording may stop.</p>{/if}
<section class="card"><h2>Files ({library.total||0})</h2>{#each library.items||[] as f}<div class="file"><button class:selected={selected===f.name} onclick={()=>selected=f.name}>{f.name}</button><span>{(f.bytes/1048576).toFixed(2)} MiB</span>{#if f.name.endsWith('.wav')}<audio controls src={authenticatedMediaUrl(`/recordings/${encodeURIComponent(f.name)}/download`)}></audio>{/if}<a href={authenticatedMediaUrl(`/recordings/${encodeURIComponent(f.name)}/download`)}>Download</a><button onclick={()=>rename(f.name)}>Rename</button><button class="danger" onclick={()=>remove(f.name)}>Delete</button></div>{:else}<p class="muted">No recordings.</p>{/each}<button disabled={page<=1} onclick={()=>{page--;load()}}>Previous</button> <button disabled={(library.items||[]).length<library.page_size} onclick={()=>{page++;load()}}>Next</button></section>
<section class="card"><h2>Annotations</h2><div class="form"><select bind:value={selected}><option value="">Select recording</option>{#each library.items||[] as f}<option value={f.name}>{f.name}</option>{/each}</select><input type="number" bind:value={offset} min="0" placeholder="Offset ms"><input bind:value={note} placeholder="Evidence note"><button onclick={annotate}>Add</button></div>{#each annotations as a}<div class="annotation"><b>{a.recording_path}</b> @{a.offset_ms} ms — {a.text}<button onclick={()=>Api.deleteRecordingAnnotation(a.id).then(load)}>Delete</button></div>{/each}</section></div>
<style>.page{padding:16px;overflow:auto;height:100%}.card{margin:12px 0;padding:14px;background:var(--bg-elev);border:1px solid var(--line);border-radius:8px}.muted{color:var(--fg-dim)}.error,.rec{color:var(--danger)}.warning{color:#f5b942;border:1px solid #f5b942;padding:10px}.vox,.vfo,.file,.form{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.vfo,.file,.annotation{padding:9px 0;border-top:1px solid var(--line)}audio{height:30px;max-width:260px}button,a,input,select{background:var(--bg);color:var(--fg);border:1px solid var(--line);padding:6px;border-radius:4px}.selected{border-color:var(--accent)}.danger{color:var(--danger)}h2{font-size:14px}</style>
