#!/usr/bin/env python3
"""Mechanically validate the Rust route inventory, docs, and TS safety boundary."""
from pathlib import Path
import re, sys
ROOT = Path(__file__).resolve().parents[1]
routes=[]
for source in sorted((ROOT/'src-tauri/src/api').glob('*.rs')):
    domain=source.stem
    text=source.read_text()
    cursor=0
    while (start := text.find('.route(', cursor)) >= 0:
        depth=0
        end=start
        for end in range(start + len('.route'), len(text)):
            if text[end] == '(': depth += 1
            elif text[end] == ')':
                depth -= 1
                if depth == 0: break
        expression=text[start:end + 1]
        cursor=end + 1
        match=re.match(r'\.route\(\s*"([^"]+)"\s*,(.*)\)$', expression, re.S)
        if not match: continue
        path, chain=match.groups()
        methods=[]
        if re.search(r'(^|\.)get\(', chain.strip()): methods.append('GET')
        if re.search(r'(^|\.)post\(', chain.strip()): methods.append('POST')
        if re.search(r'(^|\.)put\(', chain.strip()): methods.append('PUT')
        if re.search(r'(^|\.)delete\(', chain.strip()) or 'routing::delete' in chain: methods.append('DELETE')
        for method in methods: routes.append((domain, method, path))
routes.sort(key=lambda x:(x[2],x[1]))
rows=['<!-- BEGIN GENERATED ROUTE INVENTORY -->', '', '## Complete route inventory (generated)', '',
      '> Generated by `scripts/check-api-contracts.py`; both bare and `/api`-prefixed forms are served.', '',
      '| Domain | Method | Path |', '|---|---|---|']
rows += [f'| {d} | {m} | `{p}` |' for d,m,p in routes]
rows += ['', '<!-- END GENERATED ROUTE INVENTORY -->']
doc=ROOT/'docs/API.md'; text=doc.read_text()
start='<!-- BEGIN GENERATED ROUTE INVENTORY -->'; end='<!-- END GENERATED ROUTE INVENTORY -->'
block='\n'.join(rows)
if start in text:
    text=re.sub(re.escape(start)+r'.*?'+re.escape(end),block,text,flags=re.S)
else: text=text.rstrip()+'\n\n'+block+'\n'
if '--write' in sys.argv: doc.write_text(text)
elif doc.read_text()!=text:
    print('docs/API.md route inventory is stale; run scripts/check-api-contracts.py --write',file=sys.stderr);sys.exit(1)
ts=(ROOT/'ui/src/lib/api.ts').read_text()
if re.search(r'\bany\b',ts):
    print('ui/src/lib/api.ts contains forbidden any',file=sys.stderr);sys.exit(1)
if len(routes) < 190:
    print(f'route extraction unexpectedly found only {len(routes)} entries',file=sys.stderr);sys.exit(1)
print(f'validated {len(routes)} method/path contracts and TypeScript contains no any')
