//! Decoders API route composition. Handler contracts live in the parent module.

use super::*;

pub(super) fn router() -> Router<ApiState> {
    Router::new()
        .route("/decoded_messages", get(decoded_messages))
        .route("/rtl433_messages", get(rtl433_messages))
        .route("/protocol_messages", get(protocol_messages))
        .route("/aero/enable", post(aero_enable))
        .route("/aero/check", post(aero_check))
        .route("/aero/clear", post(aero_clear))
        .route("/aero/messages", get(aero_messages))
        .route("/aero/status", get(aero_status))
        .route("/aero/stderr", get(aero_stderr))
        .route("/iridium/enable", post(iridium_enable))
        .route("/iridium/check", post(iridium_check))
        .route("/iridium/clear", post(iridium_clear))
        .route("/iridium/messages", get(iridium_messages))
        .route("/iridium/status", get(iridium_status))
        .route("/iridium/quick-start", post(iridium_quick_start))
        .route("/iridium/stderr", get(iridium_stderr))
        .route("/stdc/enable", post(stdc_enable))
        .route("/stdc/check", post(stdc_check))
        .route("/stdc/clear", post(stdc_clear))
        .route("/stdc/messages", get(stdc_messages))
        .route("/stdc/status", get(stdc_status))
        .route("/gps/enable", post(gps_enable))
        .route("/gps/clear", post(gps_clear))
        .route("/gps/status", get(gps_status))
        .route("/glonass/enable", post(glonass_enable))
        .route("/glonass/clear", post(glonass_clear))
        .route("/glonass/status", get(glonass_status))
        .route("/goes_lrit/enable", post(goes_enable))
        .route("/goes_lrit/check", post(goes_check))
        .route("/goes_lrit/status", get(goes_status))
        .route(
            "/goes_lrit/satellite",
            get(goes_satellite).put(goes_satellite_put),
        )
        .route("/hd_radio/check", post(hd_radio_check))
        .route("/hd_radio/enable", post(hd_radio_enable))
        .route("/hd_radio/messages", get(hd_radio_messages))
        .route("/hd_radio/status", get(hd_radio_status))
        .route("/hd_radio/aas/:filename", get(hd_radio_aas))
        .route("/ble/devices", get(ble_devices))
        .route("/ble/status", get(ble_status))
        .route("/ble/file", get(ble_file))
        .route("/ble/clear", post(ble_clear))
        .route("/lora/messages", get(lora_messages))
        .route("/lora/regions", get(lora_regions))
        .route("/feature-packs", get(feature_packs))
        .route("/feature-packs/:id/enable", post(feature_pack_enable))
        .route("/sidecars/status", get(sidecars_status))
        .route("/sidecars/:name/stderr", get(sidecar_stderr))
        .route("/decoders/scan", get(decoders_scan))
        .route("/decoders/install/:name", post(decoders_install))
        .route("/sidecars/start_all", post(sidecars_start_all))
}
